import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NumberEditorView from "../src/views/NumberEditorView";

export default function Home() {
  const mockedProps = {
    poke: {
      id: 3,
      name: "Pikachu",
    },
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NumberEditorView props={mockedProps} />
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
}
