import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import PokemonPresenter from "../src/presenters/NumberEditorPresenter";
import NumberEditorPresenter from "../src/presenters/NumberEditorPresenter";
import PokemonModel from "../src/models/PokemonModel";

export default function Home() {
  const model = new PokemonModel();

  const mockedProps = {
    poke: {
      id: 3,
      name: "Pikachu",
    },
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NumberEditorPresenter model={model} />
        {/*  <PokemonPresenter /> */}
      </main>
      <footer className={styles.footer}>footer</footer>
    </div>
  );
}
